# =============================================================================
# PawMatch Frontend - Cloudflare Pages Configuration
# =============================================================================
# This file provides minimal configuration for Cloudflare Pages deployment.
# Dog/Cat applications are deployed as separate projects using --project-name flag:
#   - npm run deploy:dog → deploys to pawmatch-dogs project
#   - npm run deploy:cat → deploys to pawmatch-cats project
# =============================================================================

name = "pawmatch"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Note: Environment variables (NEXT_PUBLIC_PET_TYPE, etc.) are set during build time
# via the build:dog:ci and build:cat:ci scripts in package.json