# Cloudflare Pages Configuration for PawMatch

name = "pawmatch"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "pawmatch-db"
database_id = "09bcc380-4c44-4e29-9a45-6ce6def62c7f"

# Environment Variables
[vars]
ENVIRONMENT = "development"

# Build Configuration (disabled for dev)
# [build]
# command = "npm run build:check"
# cwd = "."
# watch_dir = "src"

# Routes for custom domains (optional)
# routes = [
#   { pattern = "pawmatch.your-domain.com/*", zone_name = "your-domain.com" }
# ]

# KV Namespaces (if needed for caching)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Analytics Engine (optional)
# [analytics_engine_datasets]
# binding = "ANALYTICS"

# Environment-specific configurations
[env.production]
name = "pawmatch-prod"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "pawmatch-staging"
vars = { ENVIRONMENT = "staging" }