name = "pawmatch-crawler"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 環境変数
[vars]
ALLOWED_ORIGIN = "https://pawmatch-api.elchika.app"
PET_HOME_BASE_URL = "https://www.pet-home.jp"
API_URL = "http://localhost:8787"

# R2バケット設定
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "pawmatch-images"


# D1データベース設定（APIと共有）
[[d1_databases]]
binding = "DB"
database_name = "pawmatch-db"
database_id = "09bcc380-4c44-4e29-9a45-6ce6def62c7f"

# Queue設定
[[queues.producers]]
binding = "PAWMATCH_CRAWL_QUEUE"
queue = "pawmatch-crawl-queue"

[[queues.consumers]]
queue = "pawmatch-crawl-queue"
max_batch_size = 5
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "pawmatch-crawl-dlq"

# Dead Letter Queue設定
[[queues.producers]]
binding = "PAWMATCH_CRAWL_DLQ"
queue = "pawmatch-crawl-dlq"

# Cron Trigger設定（4時間ごとに実行）
[triggers]
crons = ["0 */4 * * *"]

# Observability設定
[observability.logs]
enabled = true

# 本番環境でのGitHub Actions設定
[env.production]
vars = { GITHUB_ACTIONS = "true" }

# 開発環境設定
[env.development]  
vars = { ALLOWED_ORIGIN = "http://localhost:3004" }

# 開発サーバーポート設定
[dev]
port = 9787
inspector_port = 10230