name = "pawmatch-crawler-dev"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGIN = "http://localhost:3004"
PET_HOME_BASE_URL = "https://www.pet-home.jp"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "pawmatch-images-dev"

[[d1_databases]]
binding = "DB"
database_name = "pawmatch-db"
database_id = "local-pawmatch-db"