# =============================================================================
# PawMatch Crawler Service Configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Base Configuration
# -----------------------------------------------------------------------------
name = "pawmatch-crawler"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# -----------------------------------------------------------------------------
# Default Environment Variables
# -----------------------------------------------------------------------------
[vars]
NODE_ENV = "production"
ALLOWED_ORIGIN = "https://pawmatch-api.elchika.app"
PET_HOME_BASE_URL = "https://www.pet-home.jp"
API_URL = "https://pawmatch-api.elchika.app"
PUBLIC_API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"
CRAWLER_API_KEY = "crawler-secret-key-2024"

# -----------------------------------------------------------------------------
# Resource Bindings
# -----------------------------------------------------------------------------

# Service Bindings for internal communication
[[services]]
binding = "API_SERVICE"
service = "pawmatch-api"

# R2 Bucket (Image Storage)
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "pawmatch-images"

# D1 Database (Shared with API)
[[d1_databases]]
binding = "DB"
database_name = "pawmatch-db"
database_id = "b397c3a4-3ee4-4259-b004-6de4488e921f"
migrations_dir = "../database/migrations"

# -----------------------------------------------------------------------------
# Queue Configuration (Responsibility-based)
# -----------------------------------------------------------------------------

# Main Crawler Queue (APIから起動)
[[queues.consumers]]
queue = "pawmatch-crawler-queue"
max_batch_size = 5
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "pawmatch-crawler-dlq"
max_concurrency = 2

# Crawler Queue Producer (for DLQ)
[[queues.producers]]
binding = "PAWMATCH_CRAWLER_DLQ"
queue = "pawmatch-crawler-dlq"

# Screenshot Queue (Crawlerが処理済みデータを送信)
[[queues.producers]]
binding = "PAWMATCH_SCREENSHOT_QUEUE"
queue = "pawmatch-screenshot-queue"

# Screenshot DLQ
[[queues.producers]]
binding = "PAWMATCH_SCREENSHOT_DLQ"
queue = "pawmatch-screenshot-dlq"

# -----------------------------------------------------------------------------
# Triggers
# -----------------------------------------------------------------------------
# Cronトリガーは削除 (APIからDispatcher経由で起動される)

# -----------------------------------------------------------------------------
# Observability
# -----------------------------------------------------------------------------
[observability.logs]
enabled = true

# =============================================================================
# Environment-specific Configurations
# =============================================================================

# -----------------------------------------------------------------------------
# Production Environment
# -----------------------------------------------------------------------------
[env.production]
name = "pawmatch-crawler"

[env.production.vars]
GITHUB_ACTIONS = "true"
NODE_ENV = "production"
ALLOWED_ORIGIN = "https://pawmatch-api.elchika.app"
PET_HOME_BASE_URL = "https://www.pet-home.jp"
API_URL = "https://pawmatch-api.elchika.app"
PUBLIC_API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"
CRAWLER_API_KEY = "crawler-secret-key-2024"

# Production Resource Bindings
[[env.production.services]]
binding = "API_SERVICE"
service = "pawmatch-api"

[[env.production.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "pawmatch-images"

[[env.production.d1_databases]]
binding = "DB"
database_name = "pawmatch-db"
database_id = "b397c3a4-3ee4-4259-b004-6de4488e921f"
migrations_dir = "../database/migrations"

# Production Queue Configuration (Responsibility-based)
# Main Crawler Queue (APIから起動)
[[env.production.queues.consumers]]
queue = "pawmatch-crawler-queue"
max_batch_size = 5
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "pawmatch-crawler-dlq"
max_concurrency = 2

# Crawler Queue Producer (for DLQ)
[[env.production.queues.producers]]
binding = "PAWMATCH_CRAWLER_DLQ"
queue = "pawmatch-crawler-dlq"

# Screenshot Queue (Crawlerが処理済みデータを送信)
[[env.production.queues.producers]]
binding = "PAWMATCH_SCREENSHOT_QUEUE"
queue = "pawmatch-screenshot-queue"

# Screenshot DLQ
[[env.production.queues.producers]]
binding = "PAWMATCH_SCREENSHOT_DLQ"
queue = "pawmatch-screenshot-dlq"

# -----------------------------------------------------------------------------
# Development Environment
# -----------------------------------------------------------------------------
[env.development]
name = "pawmatch-crawler-dev"

[env.development.vars]
NODE_ENV = "development"
ALLOWED_ORIGIN = "http://localhost:3004"
PET_HOME_BASE_URL = "https://www.pet-home.jp"
API_URL = "http://localhost:9789"
PUBLIC_API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"

# -----------------------------------------------------------------------------
# Local Development Server
# -----------------------------------------------------------------------------
[dev]
port = 9787
inspector_port = 10787