name = "pawmatch-crawler"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 環境変数
[vars]
ALLOWED_ORIGIN = "https://pawmatch.elchika.app"
PET_HOME_BASE_URL = "https://pawmatch.elchika.app"

# R2バケット設定
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "pawmatch-images"

# D1データベース設定
[[d1_databases]]
binding = "DB"
database_name = "pawmatch-db"
database_id = "09bcc380-4c44-4e29-9a45-6ce6def62c7f"

# Cron Trigger設定（6時間ごとに実行）
[triggers]
crons = ["0 */6 * * *"]

# 開発環境設定
[env.development]
vars = { ALLOWED_ORIGIN = "http://localhost:3004" }