name: 'Setup PawMatch Environment'
description: 'Common setup for PawMatch workflows'

inputs:
  node-version:
    description: 'Node.js version to use'
    default: '20'
    required: false
  install-playwright:
    description: 'Whether to install Playwright'
    default: 'false'
    required: false
  install-sharp:
    description: 'Whether to install sharp'
    default: 'false'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install base dependencies
      shell: bash
      run: npm install

    - name: Install Playwright if needed
      if: inputs.install-playwright == 'true'
      shell: bash
      run: |
        npm install playwright
        npx playwright install chromium --with-deps

    - name: Install sharp if needed
      if: inputs.install-sharp == 'true'
      shell: bash
      run: |
        npm install sharp @aws-sdk/client-s3
