# =============================================================================
# Buddies Dispatcher Service Configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Base Configuration
# -----------------------------------------------------------------------------
name = "buddies-dispatcher"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# -----------------------------------------------------------------------------
# Default Environment Variables (統一プレフィックス: BUDDIES_)
# -----------------------------------------------------------------------------
[vars]
BUDDIES_NODE_ENV = "production"
BUDDIES_GITHUB_OWNER = "elchika-inc"
BUDDIES_GITHUB_REPO = "pawmatch"
BUDDIES_GITHUB_WORKFLOW_FILE = "screenshot-capture.yml"
BUDDIES_API_URL = "https://buddies-api.elchika.app"
# Note: Use `wrangler secret put BUDDIES_API_KEY --env production` for production

# -----------------------------------------------------------------------------
# Queue Configuration (Responsibility-based)
# -----------------------------------------------------------------------------

# Crawler Queue (API -> Crawler)
[[queues.producers]]
binding = "BUDDIES_CRAWLER_QUEUE"
queue = "buddies-crawler-queue"

# Screenshot Queue
[[queues.producers]]
binding = "BUDDIES_SCREENSHOT_QUEUE"
queue = "buddies-screenshot-queue"

[[queues.consumers]]
queue = "buddies-screenshot-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "buddies-screenshot-dlq"

# Conversion Queue
[[queues.producers]]
binding = "BUDDIES_CONVERSION_QUEUE"
queue = "buddies-conversion-queue"

[[queues.consumers]]
queue = "buddies-conversion-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "buddies-conversion-dlq"

# Dead Letter Queues
[[queues.producers]]
binding = "BUDDIES_SCREENSHOT_DLQ"
queue = "buddies-screenshot-dlq"

[[queues.producers]]
binding = "BUDDIES_CONVERSION_DLQ"
queue = "buddies-conversion-dlq"

# -----------------------------------------------------------------------------
# Triggers
# -----------------------------------------------------------------------------
# Cronトリガーは削除 - API経由でのDispatcher起動のみを使用

# -----------------------------------------------------------------------------
# Observability
# -----------------------------------------------------------------------------
[observability.logs]
enabled = true

# =============================================================================
# Environment-specific Configurations
# =============================================================================

# -----------------------------------------------------------------------------
# Production Environment
# -----------------------------------------------------------------------------
[env.production]
name = "buddies-dispatcher"

[env.production.vars]
BUDDIES_NODE_ENV = "production"
BUDDIES_GITHUB_OWNER = "elchika-inc"
BUDDIES_GITHUB_REPO = "pawmatch"
BUDDIES_GITHUB_WORKFLOW_FILE = "screenshot-capture.yml"
BUDDIES_API_URL = "https://buddies-api.elchika.app"

# Production Queue Configuration (Responsibility-based)
# Crawler Queue (API -> Crawler)
[[env.production.queues.producers]]
binding = "BUDDIES_CRAWLER_QUEUE"
queue = "buddies-crawler-queue"

# Screenshot Queue
[[env.production.queues.producers]]
binding = "BUDDIES_SCREENSHOT_QUEUE"
queue = "buddies-screenshot-queue"

[[env.production.queues.consumers]]
queue = "buddies-screenshot-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "buddies-screenshot-dlq"

# Conversion Queue
[[env.production.queues.producers]]
binding = "BUDDIES_CONVERSION_QUEUE"
queue = "buddies-conversion-queue"

[[env.production.queues.consumers]]
queue = "buddies-conversion-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "buddies-conversion-dlq"

# Dead Letter Queues
[[env.production.queues.producers]]
binding = "BUDDIES_SCREENSHOT_DLQ"
queue = "buddies-screenshot-dlq"

[[env.production.queues.producers]]
binding = "BUDDIES_CONVERSION_DLQ"
queue = "buddies-conversion-dlq"

# NOTE: Dispatcher does not use D1 or R2 directly (uses API instead)

# -----------------------------------------------------------------------------
# Development Environment
# -----------------------------------------------------------------------------
[env.development]
name = "buddies-dispatcher-dev"

[env.development.vars]
BUDDIES_NODE_ENV = "development"
BUDDIES_API_URL = "http://localhost:9789"
BUDDIES_API_KEY = "development-api-key-for-local-testing"

# -----------------------------------------------------------------------------
# Staging Environment
# -----------------------------------------------------------------------------
[env.staging]
name = "buddies-dispatcher-staging"

[env.staging.vars]
BUDDIES_NODE_ENV = "staging"
BUDDIES_API_URL = "https://staging-buddies-api.elchika.app"

# -----------------------------------------------------------------------------
# Local Development Server
# -----------------------------------------------------------------------------
[dev]
port = 9788
inspector_port = 10788