# =============================================================================
# PawMatch Dispatcher Service Configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Base Configuration
# -----------------------------------------------------------------------------
name = "pawmatch-dispatcher"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# -----------------------------------------------------------------------------
# Default Environment Variables (統一プレフィックス: PAWMATCH_)
# -----------------------------------------------------------------------------
[vars]
PAWMATCH_NODE_ENV = "production"
PAWMATCH_GITHUB_OWNER = "elchika-inc"
PAWMATCH_GITHUB_REPO = "pawmatch"
PAWMATCH_GITHUB_WORKFLOW_FILE = "screenshot-capture.yml"
PAWMATCH_API_URL = "https://pawmatch-api.elchika.app"
# Note: Use `wrangler secret put PAWMATCH_API_KEY --env production` for production

# -----------------------------------------------------------------------------
# Queue Configuration (Responsibility-based)
# -----------------------------------------------------------------------------

# Crawler Queue (API -> Crawler)
[[queues.producers]]
binding = "PAWMATCH_CRAWLER_QUEUE"
queue = "pawmatch-crawler-queue"

# Screenshot Queue
[[queues.producers]]
binding = "PAWMATCH_SCREENSHOT_QUEUE"
queue = "pawmatch-screenshot-queue"

[[queues.consumers]]
queue = "pawmatch-screenshot-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "pawmatch-screenshot-dlq"

# Conversion Queue
[[queues.producers]]
binding = "PAWMATCH_CONVERSION_QUEUE"
queue = "pawmatch-conversion-queue"

[[queues.consumers]]
queue = "pawmatch-conversion-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "pawmatch-conversion-dlq"

# Dead Letter Queues
[[queues.producers]]
binding = "PAWMATCH_SCREENSHOT_DLQ"
queue = "pawmatch-screenshot-dlq"

[[queues.producers]]
binding = "PAWMATCH_CONVERSION_DLQ"
queue = "pawmatch-conversion-dlq"

# -----------------------------------------------------------------------------
# Triggers
# -----------------------------------------------------------------------------
# [triggers]
# Cronトリガーは無効化 - API経由でのトリガーのみを使用
# crons = [
#   "15 */4 * * *"  # 15 minutes after crawler, every 4 hours (screenshot processing)
# ]

# -----------------------------------------------------------------------------
# Observability
# -----------------------------------------------------------------------------
[observability.logs]
enabled = true

# =============================================================================
# Environment-specific Configurations
# =============================================================================

# -----------------------------------------------------------------------------
# Production Environment
# -----------------------------------------------------------------------------
[env.production]
name = "pawmatch-dispatcher"

[env.production.vars]
PAWMATCH_NODE_ENV = "production"
PAWMATCH_GITHUB_OWNER = "elchika-inc"
PAWMATCH_GITHUB_REPO = "pawmatch"
PAWMATCH_GITHUB_WORKFLOW_FILE = "screenshot-capture.yml"
PAWMATCH_API_URL = "https://pawmatch-api.elchika.app"

# Production Queue Configuration (Responsibility-based)
# Screenshot Queue
[[env.production.queues.producers]]
binding = "PAWMATCH_SCREENSHOT_QUEUE"
queue = "pawmatch-screenshot-queue"

[[env.production.queues.consumers]]
queue = "pawmatch-screenshot-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "pawmatch-screenshot-dlq"

# Conversion Queue
[[env.production.queues.producers]]
binding = "PAWMATCH_CONVERSION_QUEUE"
queue = "pawmatch-conversion-queue"

[[env.production.queues.consumers]]
queue = "pawmatch-conversion-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "pawmatch-conversion-dlq"

# Dead Letter Queues
[[env.production.queues.producers]]
binding = "PAWMATCH_SCREENSHOT_DLQ"
queue = "pawmatch-screenshot-dlq"

[[env.production.queues.producers]]
binding = "PAWMATCH_CONVERSION_DLQ"
queue = "pawmatch-conversion-dlq"

# NOTE: Dispatcher does not use D1 or R2 directly (uses API instead)

# -----------------------------------------------------------------------------
# Development Environment
# -----------------------------------------------------------------------------
[env.development]
name = "pawmatch-dispatcher-dev"

[env.development.vars]
PAWMATCH_NODE_ENV = "development"
PAWMATCH_API_URL = "http://localhost:9789"
PAWMATCH_API_KEY = "development-api-key-for-local-testing"

# -----------------------------------------------------------------------------
# Staging Environment
# -----------------------------------------------------------------------------
[env.staging]
name = "pawmatch-dispatcher-staging"

[env.staging.vars]
PAWMATCH_NODE_ENV = "staging"
PAWMATCH_API_URL = "https://staging-pawmatch-api.elchika.app"

# -----------------------------------------------------------------------------
# Local Development Server
# -----------------------------------------------------------------------------
[dev]
port = 9788
inspector_port = 10788