# =============================================================================
# PawMatch Dispatcher Service Configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Base Configuration
# -----------------------------------------------------------------------------
name = "pawmatch-dispatcher"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# -----------------------------------------------------------------------------
# Default Environment Variables
# -----------------------------------------------------------------------------
[vars]
NODE_ENV = "production"
GITHUB_OWNER = "elchika-inc"
GITHUB_REPO = "pawmatch"
WORKFLOW_FILE = "automated-screenshot-capture.yml"
API_URL = "https://pawmatch-api.elchika.app"
PUBLIC_API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"

# -----------------------------------------------------------------------------
# Queue Configuration
# -----------------------------------------------------------------------------

# Main Dispatch Queue
[[queues.producers]]
binding = "PAWMATCH_DISPATCH_QUEUE"
queue = "pawmatch-dispatch-queue"

[[queues.consumers]]
queue = "pawmatch-dispatch-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "pawmatch-dispatch-dlq"

# Dead Letter Queue
[[queues.producers]]
binding = "PAWMATCH_DISPATCH_DLQ"
queue = "pawmatch-dispatch-dlq"

# -----------------------------------------------------------------------------
# Triggers
# -----------------------------------------------------------------------------
[triggers]
crons = [
  "15 */4 * * *"  # 15 minutes after crawler, every 4 hours (screenshot processing)
]

# -----------------------------------------------------------------------------
# Observability
# -----------------------------------------------------------------------------
[observability.logs]
enabled = true

# =============================================================================
# Environment-specific Configurations
# =============================================================================

# -----------------------------------------------------------------------------
# Production Environment
# -----------------------------------------------------------------------------
[env.production]
name = "pawmatch-dispatcher"

[env.production.vars]
NODE_ENV = "production"
GITHUB_OWNER = "elchika-inc"
GITHUB_REPO = "pawmatch"
WORKFLOW_FILE = "automated-screenshot-capture.yml"
API_URL = "https://pawmatch-api.elchika.app"
PUBLIC_API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"

# Production Queue Configuration
[[env.production.queues.producers]]
binding = "PAWMATCH_DISPATCH_QUEUE"
queue = "pawmatch-dispatch-queue"

[[env.production.queues.consumers]]
queue = "pawmatch-dispatch-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "pawmatch-dispatch-dlq"

[[env.production.queues.producers]]
binding = "PAWMATCH_DISPATCH_DLQ"
queue = "pawmatch-dispatch-dlq"

# NOTE: Dispatcher does not use D1 or R2 directly (uses API instead)

# -----------------------------------------------------------------------------
# Development Environment
# -----------------------------------------------------------------------------
[env.development]
name = "pawmatch-dispatcher-dev"

[env.development.vars]
NODE_ENV = "development"
GITHUB_OWNER = "elchika-inc"
GITHUB_REPO = "pawmatch"
WORKFLOW_FILE = "automated-screenshot-capture.yml"
API_URL = "http://localhost:9789"
PUBLIC_API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"

# -----------------------------------------------------------------------------
# Local Development Server
# -----------------------------------------------------------------------------
[dev]
port = 9788
inspector_port = 10788