# =============================================================================
# Buddies Admin Service Configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Base Configuration
# -----------------------------------------------------------------------------
name = "buddies-admin"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# -----------------------------------------------------------------------------
# Default Environment Variables
# -----------------------------------------------------------------------------
[vars]
NODE_ENV = "development"
# カンマ区切りで許可するIPアドレスを指定（空文字列の場合はすべてのIPを許可）
ALLOWED_IPS = ""
# 管理者認証用シークレット（本番環境では必ず変更すること）
ADMIN_SECRET = "development-secret-key-change-in-production"

# -----------------------------------------------------------------------------
# Resource Bindings
# -----------------------------------------------------------------------------

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "buddies-db"
database_id = "1908aab6-5ff7-4aa3-9bd1-372f01544b7f"

# KV Namespace (API Keys Cache)
[[kv_namespaces]]
binding = "API_KEYS_CACHE"
id = "2423ded5fcce4888b7f6c5ecbddd1b5a"

# R2 Bucket (Image Storage)
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "buddies-images"

# =============================================================================
# Environment-specific Configurations
# =============================================================================

# -----------------------------------------------------------------------------
# Production Environment
# -----------------------------------------------------------------------------
[env.production]
name = "buddies-admin"

[env.production.vars]
NODE_ENV = "production"
# Cloudflare Accessで制限するため、IP制限は無効化
ALLOWED_IPS = ""
# 本番環境では必ず強力なシークレットに変更すること
ADMIN_SECRET = "production-secret-key-please-change"

[[env.production.d1_databases]]
binding = "DB"
database_name = "buddies-db"
database_id = "1908aab6-5ff7-4aa3-9bd1-372f01544b7f"

[[env.production.kv_namespaces]]
binding = "API_KEYS_CACHE"
id = "2423ded5fcce4888b7f6c5ecbddd1b5a"

[[env.production.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "buddies-images"

# -----------------------------------------------------------------------------
# Development Environment
# -----------------------------------------------------------------------------
[env.development]
name = "buddies-admin-dev"

[env.development.vars]
NODE_ENV = "development"
ALLOWED_IPS = ""
ADMIN_SECRET = "development-secret-key"

# -----------------------------------------------------------------------------
# Local Development Server
# -----------------------------------------------------------------------------
[dev]
port = 8788
inspector_port = 10788