# Cloudflare Pages設定（Buddies LP）

name = "buddies-lp"
compatibility_date = "2024-01-01"

# Pages設定
pages_build_output_dir = "out"

# カスタムドメイン設定は Cloudflare ダッシュボードから行います
# Pages → buddies-lp → Custom domains
