name = "pawmatch-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 環境変数
[vars]
ALLOWED_ORIGIN = "*"

# R2バケット設定（画像配信用）
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "pawmatch-images"

# D1データベース設定
[[d1_databases]]
binding = "DB"
database_name = "pawmatch-db"
database_id = "09bcc380-4c44-4e29-9a45-6ce6def62c7f"
migrations_dir = "migrations"

# Service Binding - 画像変換Worker
[[services]]
binding = "IMAGE_WORKER"
service = "pawmatch-image-converter"
environment = "production"

# Observability設定
[observability.logs]
enabled = true

# カスタムドメイン設定
[env.production]
vars = { ALLOWED_ORIGIN = "https://pawmatch-dogs.elchika.app,https://pawmatch-cats.elchika.app" }
route = { pattern = "pawmatch-api.elchika.app/*", zone_name = "elchika.app" }

# 開発環境設定
[env.development]
vars = { ALLOWED_ORIGIN = "http://localhost:3004" }

# 開発サーバーポート設定
[dev]
port = 8787
inspector_port = 10229