# =============================================================================
# Buddies API Service Configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Base Configuration
# -----------------------------------------------------------------------------
name = "buddies-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# -----------------------------------------------------------------------------
# Default Environment Variables
# -----------------------------------------------------------------------------
[vars]
NODE_ENV = "production"
ALLOWED_ORIGIN = "*"
ALLOWED_ORIGINS = "https://buddies-api.elchika.app,http://localhost:8787"
API_BASE_URL = "https://buddies-api.elchika.app"
API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"
PUBLIC_API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"
CRAWLER_API_KEY = "crawler-secret-key-2024"

# -----------------------------------------------------------------------------
# Resource Bindings
# -----------------------------------------------------------------------------

# Service Bindings
[[services]]
binding = "DISPATCHER"
service = "buddies-dispatcher"

[[services]]
binding = "CRAWLER_SERVICE"
service = "buddies-crawler"

# Queue Producer removed - Crawler is now triggered via Dispatcher
# [[queues.producers]]
# binding = "CRAWLER_QUEUE"
# queue = "buddies-crawler-queue"

# KV Namespace (API Key Cache)
[[kv_namespaces]]
binding = "API_KEYS_CACHE"
id = "2423ded5fcce4888b7f6c5ecbddd1b5a"
preview_id = "2423ded5fcce4888b7f6c5ecbddd1b5a"

# KV Namespace (Rate Limiting) - Disabled until properly configured
# [[kv_namespaces]]
# binding = "RATE_LIMIT_KV"
# id = "rate-limit-kv-id"
# preview_id = "rate-limit-kv-preview-id"

# R2 Bucket (Image Storage)
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "buddies-images"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "buddies-db"
database_id = "1908aab6-5ff7-4aa3-9bd1-372f01544b7f"
migrations_dir = "../database/migrations"

# -----------------------------------------------------------------------------
# Observability
# -----------------------------------------------------------------------------
[observability.logs]
enabled = true

# -----------------------------------------------------------------------------
# Cron Triggers
# -----------------------------------------------------------------------------
[triggers]
crons = ["0 */4 * * *"] # 4時間ごとに実行

# =============================================================================
# Environment-specific Configurations
# =============================================================================

# -----------------------------------------------------------------------------
# Production Environment
# -----------------------------------------------------------------------------
[env.production]
name = "buddies-api"
route = { pattern = "buddies-api.elchika.app/*", zone_name = "elchika.app" }

[env.production.vars]
NODE_ENV = "production"
ALLOWED_ORIGIN = "https://buddies-dogs.elchika.app,https://buddies-cats.elchika.app"
ALLOWED_ORIGINS = "https://buddies-dogs.elchika.app,https://buddies-cats.elchika.app"
API_BASE_URL = "https://buddies-api.elchika.app"
API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"
PUBLIC_API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"
CRAWLER_API_KEY = "crawler-secret-key-2024"

[[env.production.services]]
binding = "DISPATCHER"
service = "buddies-dispatcher"

[[env.production.services]]
binding = "CRAWLER_SERVICE"
service = "buddies-crawler"

# Queue Producer removed - Crawler is now triggered via Dispatcher
# [[env.production.queues.producers]]
# binding = "CRAWLER_QUEUE"
# queue = "buddies-crawler-queue"

[[env.production.kv_namespaces]]
binding = "API_KEYS_CACHE"
id = "ec30a1e116fb42c081ad0b7f07d413da"

# [[env.production.kv_namespaces]]
# binding = "RATE_LIMIT_KV"
# id = "rate-limit-kv-id"

[[env.production.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "buddies-images"

[[env.production.d1_databases]]
binding = "DB"
database_name = "buddies-db"
database_id = "1908aab6-5ff7-4aa3-9bd1-372f01544b7f"
migrations_dir = "../database/migrations"

# -----------------------------------------------------------------------------
# Development Environment
# -----------------------------------------------------------------------------
[env.development]
name = "buddies-api-dev"

[env.development.vars]
NODE_ENV = "development"
ALLOWED_ORIGIN = "http://localhost:3004"
ALLOWED_ORIGINS = "http://localhost:3004,http://localhost:3000"
API_BASE_URL = "http://localhost:9789"
PUBLIC_API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"

# -----------------------------------------------------------------------------
# Local Development Server
# -----------------------------------------------------------------------------
[dev]
port = 9789
inspector_port = 10789
