# =============================================================================
# PawMatch API Service Configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Base Configuration
# -----------------------------------------------------------------------------
name = "pawmatch-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# -----------------------------------------------------------------------------
# Default Environment Variables
# -----------------------------------------------------------------------------
[vars]
NODE_ENV = "production"
ALLOWED_ORIGIN = "*"
ALLOWED_ORIGINS = "https://pawmatch-api.elchika.app,http://localhost:8787"
API_BASE_URL = "https://pawmatch-api.elchika.app"
PUBLIC_API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"
CRAWLER_API_KEY = "crawler-secret-key-2024"

# -----------------------------------------------------------------------------
# Resource Bindings
# -----------------------------------------------------------------------------

# Service Bindings
[[services]]
binding = "DISPATCHER"
service = "pawmatch-dispatcher"

[[services]]
binding = "CRAWLER_SERVICE"
service = "pawmatch-crawler"

# Queue Producer (Crawler Queue)
[[queues.producers]]
binding = "CRAWLER_QUEUE"
queue = "pawmatch-crawler-queue"

# KV Namespace (API Key Cache)
[[kv_namespaces]]
binding = "API_KEYS_CACHE"
id = "ec30a1e116fb42c081ad0b7f07d413da"
preview_id = "ec30a1e116fb42c081ad0b7f07d413da"

# R2 Bucket (Image Storage)
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "pawmatch-images"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "pawmatch-db"
database_id = "b397c3a4-3ee4-4259-b004-6de4488e921f"
migrations_dir = "../database/migrations"

# -----------------------------------------------------------------------------
# Observability
# -----------------------------------------------------------------------------
[observability.logs]
enabled = true

# -----------------------------------------------------------------------------
# Cron Triggers
# -----------------------------------------------------------------------------
[triggers]
crons = ["0 */4 * * *"] # 4時間ごとに実行

# =============================================================================
# Environment-specific Configurations
# =============================================================================

# -----------------------------------------------------------------------------
# Production Environment
# -----------------------------------------------------------------------------
[env.production]
name = "pawmatch-api"
route = { pattern = "pawmatch-api.elchika.app/*", zone_name = "elchika.app" }

[env.production.vars]
NODE_ENV = "production"
ALLOWED_ORIGIN = "https://pawmatch-dogs.elchika.app,https://pawmatch-cats.elchika.app"
ALLOWED_ORIGINS = "https://pawmatch-dogs.elchika.app,https://pawmatch-cats.elchika.app"
API_BASE_URL = "https://pawmatch-api.elchika.app"
PUBLIC_API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"
CRAWLER_API_KEY = "crawler-secret-key-2024"

[[env.production.services]]
binding = "DISPATCHER"
service = "pawmatch-dispatcher"

[[env.production.services]]
binding = "CRAWLER_SERVICE"
service = "pawmatch-crawler"

[[env.production.queues.producers]]
binding = "CRAWLER_QUEUE"
queue = "pawmatch-crawler-queue"

[[env.production.kv_namespaces]]
binding = "API_KEYS_CACHE"
id = "ec30a1e116fb42c081ad0b7f07d413da"

[[env.production.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "pawmatch-images"

[[env.production.d1_databases]]
binding = "DB"
database_name = "pawmatch-db"
database_id = "b397c3a4-3ee4-4259-b004-6de4488e921f"
migrations_dir = "../database/migrations"

# -----------------------------------------------------------------------------
# Development Environment
# -----------------------------------------------------------------------------
[env.development]
name = "pawmatch-api-dev"

[env.development.vars]
NODE_ENV = "development"
ALLOWED_ORIGIN = "http://localhost:3004"
ALLOWED_ORIGINS = "http://localhost:3004,http://localhost:3000"
API_BASE_URL = "http://localhost:9789"
PUBLIC_API_KEY = "b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb"

# -----------------------------------------------------------------------------
# Local Development Server
# -----------------------------------------------------------------------------
[dev]
port = 9789
inspector_port = 10789
