# 画像変換専用Worker設定
name = "pawmatch-image-worker"
main = "src/image-worker.js"
compatibility_date = "2024-01-01"
workers_dev = false

# カスタムドメイン（必要に応じて設定）
# route = "images.pawmatch.jp/*"

# 環境変数
[vars]
CF_IMAGE_RESIZING_URL = ""  # Cloudflare Image Resizing APIのURL（オプション）
GITHUB_OWNER = "elchika"
GITHUB_REPO = "pawmatch"

# R2バケットバインディング
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pawmatch-images"

# D1データベースバインディング
[[d1_databases]]
binding = "DB"
database_name = "pawmatch-db"
database_id = "YOUR_DATABASE_ID"

# 定期実行（画像ステータスチェック）
[triggers]
crons = ["0 */12 * * *"]  # 12時間ごとに実行

# 開発環境設定
[env.development]
vars = { ENVIRONMENT = "development" }

[[env.development.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pawmatch-images-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "pawmatch-db-dev"
database_id = "YOUR_DEV_DATABASE_ID"

# 本番環境設定
[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "pawmatch-images"

[[env.production.d1_databases]]
binding = "DB"
database_name = "pawmatch-db"
database_id = "YOUR_PROD_DATABASE_ID"