name: Deploy to Cloudflare

on:
  workflow_run:
    workflows: ['Test and Build']
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    # Test and Buildワークフローが成功した場合のみ実行
    # pushイベントまたはPRマージ（push）の場合のみデプロイ
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Apply database migrations
        run: |
          cd api
          npx wrangler d1 migrations apply pawmatch-db --remote || echo "Migrations may have already been applied"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Create Cloudflare Queues
        run: |
          cd api
          npx wrangler queues create pawmatch-crawler-queue || echo "Queue may already exist"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy all services
        run: npm run deploy:all
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
