name: Test and Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Frontend linter
        run: npm run lint:app
        continue-on-error: true

      - name: Run Dispatcher linter
        run: npm run lint:dispatcher
        continue-on-error: true

  type-check:
    name: Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Frontend type check
        run: npm run type-check:app

      - name: Run API type check
        run: npm run type-check:api

      - name: Run Crawler type check
        run: npm run type-check:crawler

      - name: Run Dispatcher type check
        run: npm run type-check:dispatcher

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Frontend tests
        run: npm run test:app
        continue-on-error: true # テストがまだ実装されていない場合のため

      - name: Run Dispatcher tests
        run: npm run test:dispatcher
        continue-on-error: true # テストがまだ実装されていない場合のため

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, type-check]

    strategy:
      matrix:
        workspace: [frontend, api, crawler, dispatcher]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build ${{ matrix.workspace }}
        run: |
          if [[ "${{ matrix.workspace }}" == "frontend" ]]; then
            npm run build:app
          elif [[ "${{ matrix.workspace }}" == "dispatcher" ]]; then
            npm run build:dispatcher
          else
            npm run build -w @pawmatch/${{ matrix.workspace }}
          fi
        continue-on-error: ${{ matrix.workspace != 'frontend' }} # frontendのみ必須

  all-checks-passed:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs: [lint, type-check, test, build]
    if: always()

    steps:
      - name: Check results
        run: |
          echo "CI Pipeline Results:"
          echo "===================="
          echo "Lint: ${{ needs.lint.result }}"
          echo "Type Check: ${{ needs.type-check.result }}"
          echo "Test: ${{ needs.test.result }}"
          echo "Build: ${{ needs.build.result }}"

          if [[ "${{ needs.lint.result }}" == "failure" ]] || \
             [[ "${{ needs.type-check.result }}" == "failure" ]] || \
             [[ "${{ needs.build.result }}" == "failure" ]]; then
            echo "❌ CI checks failed!"
            exit 1
          else
            echo "✅ All CI checks passed!"
          fi
