name: Test and Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint

      - name: Run type check
        run: npm run type-check

      - name: Run tests
        run: npm run test
        continue-on-error: true

  build-frontend:
    name: Build Frontend (${{ matrix.pet-type }})
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        pet-type: [dog, cat]
        include:
          - pet-type: dog
            app-name: DogMatch
            app-url: https://dogmatch.elchika.app
          - pet-type: cat
            app-name: CatMatch
            app-url: https://catmatch.elchika.app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build frontend for ${{ matrix.pet-type }}
        env:
          NEXT_PUBLIC_PET_TYPE: ${{ matrix.pet-type }}
          NEXT_PUBLIC_API_URL: https://pawmatch-api.elchika.app
          NEXT_PUBLIC_API_KEY: b80f83e113c5463a811607a30afd133dbb0b3c39a0eb41ebac716e29eeda27fb
          NEXT_PUBLIC_USE_API: true
          NEXT_PUBLIC_APP_NAME: ${{ matrix.app-name }}
          NEXT_PUBLIC_APP_URL: ${{ matrix.app-url }}
          NEXT_TELEMETRY_DISABLED: 1
          NODE_OPTIONS: --max-old-space-size=4096
        run: npm run build -w @pawmatch/frontend

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-${{ matrix.pet-type }}-build
          path: frontend/.next
          retention-days: 1

  build-workers:
    name: Build Workers
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build API
        run: npm run build -w @pawmatch/api
        continue-on-error: true

      - name: Build Crawler
        run: npm run build -w @pawmatch/crawler
        continue-on-error: true

      - name: Build Dispatcher
        run: npm run build -w @pawmatch/dispatcher
        continue-on-error: true
